In [74]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

In [75]:
URL = 'https://www.opensecrets.org/races/summary.csv?cycle=2020&id=TN07'
response = requests.get(URL)
print(type(response))
if response.status_code == requests.codes.ok:
    print('Request is okay!')
else:
    response.raise_for_status()
TN_district7 = pd.read_csv(StringIO(response.text), sep=',')
TN_district7

<class 'requests.models.Response'>
Request is okay!

,cid,FirstLastP,Rcpts,Spent,PACs,Indivs,Cand,Other,EndCash,LgIndivs,...,Result,CRPICO,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote
0,N00041873,Mark Green (R),1194960.47,935486.67,171900.0,819151.42,0.0,203909.05,287888.55,819151.42,...,W,I,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,TN07,0,1,N
1,N00045536,Kiran Sreepada (D),206644.28,207190.98,4000.0,202644.28,0.0,0.00,0.00,179129.75,...,L,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,,0,2,N
2,N00047077,Ronald Brown (I),1750.00,0.00,0.0,1750.00,0.0,0.00,9006.00,300.00,...,L,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,,0,2,N
3,N00046592,Scott Vieira Jr (I),655.47,1048.51,10.0,45.00,35.0,565.47,-196.52,0.00,...,L,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,,0,2,N
4,N00045535,Benjamin Estes (3),0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,...,,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,NaN,0,2,N

In [76]:
URL = 'https://en.wikipedia.org/wiki/List_of_U.S._state_and_territory_abbreviations'
states_df = pd.read_html(URL)[1]
states_df.columns = states_df.columns.map(lambda x: x[1])
states_df = (
    states_df
    .reset_index()
    .drop(columns = ['index', 'Status of region', 'Unnamed: 2_level_1', 'Unnamed: 4_level_1', 'Unnamed: 5_level_1', 'Unnamed: 6_level_1', 'GPO', 'AP', 'Other abbreviations'])
    .dropna()
    .rename(columns = {'Name': 'State', 'Unnamed: 3_level_1': 'Abbreviation'})
    .drop(0).reset_index(drop=True)
)
states_abr_dict = states_df.set_index('State')['Abbreviation'].to_dict()
states_abr_dict

{'Alabama': 'AL',
 'Alaska': 'AK',
 'Arizona': 'AZ',
 'Arkansas': 'AR',
 'California': 'CA',
 'Colorado': 'CO',
 'Connecticut': 'CT',
 'Delaware': 'DE',
 'District of Columbia': 'DC',
 'Florida': 'FL',
 'Georgia': 'GA',
 'Hawaii': 'HI',
 'Idaho': 'ID',
 'Illinois': 'IL',
 'Indiana': 'IN',
 'Iowa': 'IA',
 'Kansas': 'KS',
 'Kentucky': 'KY',
 'Louisiana': 'LA',
 'Maine': 'ME',
 'Maryland': 'MD',
 'Massachusetts': 'MA',
 'Michigan': 'MI',
 'Minnesota': 'MN',
 'Mississippi': 'MS',
 'Missouri': 'MO',
 'Montana': 'MT',
 'Nebraska': 'NE',
 'Nevada': 'NV',
 'New Hampshire': 'NH',
 'New Jersey': 'NJ',
 'New Mexico': 'NM',
 'New York': 'NY',
 'North Carolina': 'NC',
 'North Dakota': 'ND',
 'Ohio': 'OH',
 'Oklahoma': 'OK',
 'Oregon': 'OR',
 'Pennsylvania': 'PA',
 'Rhode Island': 'RI',
 'South Carolina': 'SC',
 'South Dakota': 'SD',
 'Tennessee': 'TN',
 'Texas': 'TX',
 'Utah': 'UT',
 'Vermont': 'VT',
 'Virginia': 'VA',
 'Washington': 'WA',
 'West Virginia': 'WV',
 'Wisconsin': 'WI',
 'Wyoming': 'WY',
 'American Samoa': 'AS',
 'Guam': 'GU',
 'Northern Mariana Islands': 'MP',
 'Puerto Rico': 'PR',
 'U.S. Virgin Islands': 'VI',
 'U.S. Minor Outlying Islands': 'UM',
 'Marshall Islands': 'MH',
 'Micronesia': 'FM',
 'Palau': 'PW'}

In [77]:
URL = 'https://en.wikipedia.org/wiki/2020_United_States_House_of_Representatives_elections'
response = requests.get(URL)
if response.status_code == requests.codes.ok:
    soup = BeautifulSoup(response.text, features="html.parser")
else:
    response.raise_for_status()
tables_html = str(soup.find_all('table', attrs={'class' : 'wikitable'}))
all_states_df = pd.read_html(StringIO(str(tables_html)))[1].fillna('-')
all_states_df.columns = all_states_df.columns.map(lambda x: x[1])
all_states_df = all_states_df.drop(columns=['Seats', 'Change'])
all_states_df.head(3)
state_representatives_df = pd.merge(left=all_states_df, right=states_df, on='State')
state_representatives_df

             State  Total seats Abbreviation
0          Alabama            7           AL
1           Alaska            1           AK
2          Arizona            9           AZ
3         Arkansas            4           AR
4       California           53           CA
5         Colorado            7           CO
6      Connecticut            5           CT
7         Delaware            1           DE
8          Florida           27           FL
9          Georgia           14           GA
10          Hawaii            2           HI
11           Idaho            2           ID
12        Illinois           18           IL
13         Indiana            9           IN
14            Iowa            4           IA
15          Kansas            4           KS
16        Kentucky            6           KY
17       Louisiana            6           LA
18           Maine            2           ME
19        Maryland            8           MD
20   Massachusetts            9           MA
21        Michigan           14           MI
22       Minnesota            8           MN
23     Mississippi            4           MS
24        Missouri            8           MO
25         Montana            1           MT
26        Nebraska            3           NE
27          Nevada            4           NV
28   New Hampshire            2           NH
29      New Jersey           12           NJ
30      New Mexico            3           NM
31        New York           27           NY
32  North Carolina           13           NC
33    North Dakota            1           ND
34            Ohio           16           OH
35        Oklahoma            5           OK
36          Oregon            5           OR
37    Pennsylvania           18           PA
38    Rhode Island            2           RI
39  South Carolina            7           SC
40    South Dakota            1           SD
41       Tennessee            9           TN
42           Texas           36           TX
43            Utah            4           UT
44         Vermont            1           VT
45        Virginia           11           VA
46      Washington           10           WA
47   West Virginia            3           WV
48       Wisconsin            8           WI
49         Wyoming            1           WY

In [78]:
def ensure_two_digits(num):
    #Ensures an integer is represented by two digits, padding with '0' if necessary.
    return str(num).zfill(2)
    
def retrieve_2020_state_district_data(state: str, district: int, state_abbreviations=False):
    #need some kind of dictionary that will take state name if state_abbreviations=False
    state_abr_dict = states_abr_dict
    base_url = 'https://www.opensecrets.org/races/summary.csv?cycle=2020&id='
    district_num = ensure_two_digits(district)
    if state_abbreviations:
        state_district_url = base_url+state+district_num
    else:
        state_district_url = base_url+state_abr_dict[state]+district_num
    response = requests.get(state_district_url)
    if response.status_code != requests.codes.ok:
        response.raise_for_status()
        #print('Check to see if state has this District number')
    state_distr_df = pd.read_csv(StringIO(response.text), sep=',')
    state_distr_df.insert(0, 'State_Abbreviation', state if state_abbreviations else state_abr_dict[state])
    state_distr_df.insert(1, 'District', district_num)
    return state_distr_df

retrieve_2020_state_district_data('Connecticut', 2, state_abbreviations=False)

,State_Abbreviation,District,cid,FirstLastP,Rcpts,Spent,PACs,Indivs,Cand,Other,...,Result,CRPICO,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote
0,CT,02,N00024842,Joe Courtney (D),964731.32,999359.87,587250.0,363656.46,105.1,13719.76,...,W,I,Connecticut,NaN,NaN,2020-08-11 00:00:00 +0000,CT02,0,1,N
1,CT,02,N00045015,Justin Anderson (R),80227.41,78767.12,0.0,27837.71,52089.7,300.00,...,L,C,Connecticut,NaN,NaN,2020-08-11 00:00:00 +0000,,0,2,N
2,CT,02,N00047360,Cassandra Martineau (3),0.00,0.00,0.0,0.00,0.0,0.00,...,,C,Connecticut,NaN,NaN,2020-08-11 00:00:00 +0000,NaN,0,2,N
3,CT,02,N00029657,Daniel Reale (L),0.00,0.00,0.0,0.00,0.0,0.00,...,,C,Connecticut,NaN,NaN,2020-08-11 00:00:00 +0000,NaN,0,2,N

In [80]:
import tqdm

def get_all_data(state_representatives_df):
    #Tennessee       TN   7
    #Massachusetts   MA   6
    #state_abr_list = state_representatives_df['State_Abbreviation'].to_list()
    #state_rep_num = state_representatives_df['Number_of_Representatives'].to_list()
    state_district_dict = state_representatives_df.set_index('Abbreviation')['Total seats'].to_dict()
    print(state_district_dict)
    data_list = []
    result_df = pd.DataFrame()
    for state in tqdm.tqdm(state_district_dict):
        for district in range(1, state_district_dict[state]):
            data_list.append(retrieve_2020_state_district_data(state, district, state_abbreviations=True))
    for data_df in data_list:
        result_df = pd.concat([result_df, data_df])
    return result_df

get_all_data(state_representatives_df)

{'AL': 7, 'AK': 1, 'AZ': 9, 'AR': 4, 'CA': 53, 'CO': 7, 'CT': 5, 'DE': 1, 'FL': 27, 'GA': 14, 'HI': 2, 'ID': 2, 'IL': 18, 'IN': 9, 'IA': 4, 'KS': 4, 'KY': 6, 'LA': 6, 'ME': 2, 'MD': 8, 'MA': 9, 'MI': 14, 'MN': 8, 'MS': 4, 'MO': 8, 'MT': 1, 'NE': 3, 'NV': 4, 'NH': 2, 'NJ': 12, 'NM': 3, 'NY': 27, 'NC': 13, 'ND': 1, 'OH': 16, 'OK': 5, 'OR': 5, 'PA': 18, 'RI': 2, 'SC': 7, 'SD': 1, 'TN': 9, 'TX': 36, 'UT': 4, 'VT': 1, 'VA': 11, 'WA': 10, 'WV': 3, 'WI': 8, 'WY': 1}

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 50/50 [00:45<00:00,  1.10it/s]

,State_Abbreviation,District,cid,FirstLastP,Rcpts,Spent,PACs,Indivs,Cand,Other,...,Result,CRPICO,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote
0,AL,01,N00044245,Jerry Carl (R),1971321.50,1859348.91,387000.00,1044195.95,434655.50,105470.05,...,W,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
1,AL,01,N00044750,James Averhart (D),80094.95,78973.24,0.00,50849.95,29245.00,0.00,...,L,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
0,AL,02,N00041295,Barry Moore (R),650806.75,669367.70,230281.65,408536.20,11500.00,488.90,...,W,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
1,AL,02,N00045944,Phyllis Harvey-Hall (D),56049.68,55988.07,2032.00,42411.95,10575.41,1030.32,...,L,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
2,AL,02,N00045631,John Page (L),0.00,0.00,0.00,0.00,0.00,0.00,...,,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,NaN,0,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,WI,06,N00036409,Glenn Grothman (R),1815756.42,1736659.09,386783.88,1296505.89,0.00,132466.65,...,W,I,Wisconsin,NaN,NaN,2020-08-11 00:00:00 +0000,WI06,0,1,N
1,WI,06,N00045562,Jessica King (D),287752.83,245787.59,29824.64,247004.58,2591.01,8332.60,...,L,C,Wisconsin,NaN,NaN,2020-08-11 00:00:00 +0000,,0,2,N
2,WI,06,N00046453,Fredrick Erickson (3),0.00,0.00,0.00,0.00,0.00,0.00,...,,C,Wisconsin,NaN,NaN,2020-08-11 00:00:00 +0000,NaN,0,2,N
0,WI,07,N00045307,Tom Tiffany (R),2637459.08,2514739.74,363117.39,2235625.83,0.00,38715.86,...,W,I,Wisconsin,NaN,NaN,2020-08-11 00:00:00 +0000,WI07,0,1,N
1,WI,07,N00045620,Tricia Zunker (D),1261957.30,1232690.26,91806.63,1166874.67,0.00,3276.00,...,L,C,Wisconsin,NaN,NaN,2020-08-11 00:00:00 +0000,,0,2,N